"""setup db

Revision ID: 9f89047e077a
Revises: 
Create Date: 2025-11-29 07:46:51.825401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f89047e077a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('codename'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_group_codename', 'group', ['codename'], unique=False)
    op.create_index('ix_group_is_active', 'group', ['is_active'], unique=False)
    op.create_table('permission',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('codename'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_permission_category', 'permission', ['category'], unique=False)
    op.create_index('ix_permission_codename', 'permission', ['codename'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('phone_number', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('profile_accessibility', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('is_trashed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_user_name', 'user', ['user_name'], unique=False)
    op.create_table('activity_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_activity_log_action', 'activity_log', ['action'], unique=False)
    op.create_index('ix_activity_log_created_at', 'activity_log', ['created_at'], unique=False)
    op.create_index('ix_activity_log_ip_address', 'activity_log', ['ip_address'], unique=False)
    op.create_index('ix_activity_log_level', 'activity_log', ['level'], unique=False)
    op.create_index('ix_activity_log_module', 'activity_log', ['module'], unique=False)
    op.create_index('ix_activity_log_request_id', 'activity_log', ['request_id'], unique=False)
    op.create_index('ix_activity_log_session_id', 'activity_log', ['session_id'], unique=False)
    op.create_index('ix_activity_log_user_id', 'activity_log', ['user_id'], unique=False)
    op.create_table('group_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'permission_id', name='uq_group_permission')
    )
    op.create_index('ix_group_permission_group_id', 'group_permission', ['group_id'], unique=False)
    op.create_index('ix_group_permission_permission_id', 'group_permission', ['permission_id'], unique=False)
    op.create_table('user_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index('ix_user_group_group_id', 'user_group', ['group_id'], unique=False)
    op.create_index('ix_user_group_user_id', 'user_group', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_group_user_id', table_name='user_group')
    op.drop_index('ix_user_group_group_id', table_name='user_group')
    op.drop_table('user_group')
    op.drop_index('ix_group_permission_permission_id', table_name='group_permission')
    op.drop_index('ix_group_permission_group_id', table_name='group_permission')
    op.drop_table('group_permission')
    op.drop_index('ix_activity_log_user_id', table_name='activity_log')
    op.drop_index('ix_activity_log_session_id', table_name='activity_log')
    op.drop_index('ix_activity_log_request_id', table_name='activity_log')
    op.drop_index('ix_activity_log_module', table_name='activity_log')
    op.drop_index('ix_activity_log_level', table_name='activity_log')
    op.drop_index('ix_activity_log_ip_address', table_name='activity_log')
    op.drop_index('ix_activity_log_created_at', table_name='activity_log')
    op.drop_index('ix_activity_log_action', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index('ix_user_user_name', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_permission_codename', table_name='permission')
    op.drop_index('ix_permission_category', table_name='permission')
    op.drop_table('permission')
    op.drop_index('ix_group_is_active', table_name='group')
    op.drop_index('ix_group_codename', table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
